
project_id = "axamyiyfsajjpfghwckr"

[functions.process-flashcards]
verify_jwt = true

[functions.convert-file]
verify_jwt = false

[functions.generate-infographic]
verify_jwt = true

[api.jwt]
middleware.keys = ["public_key", "private_key"]

[api]
enabled_apis = ["rest", "realtime", "storage", "auth"]
